export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";



export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILED = "AUTH_USER_FAILED"

export const GET_CURRENT_USER_START = "GET_CURRENT_USER_START";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_USER_FAILED = "GET_CURRENT_USER_FAILED"

//
export const GET_ALL_VENDORS = "GET_ALL_VENDORS";
export const GET_ALL_VENDORS_SUCESS = "GET_ALL_VENDORS_SUCESS";
export const GET_ALL_VENDORS_FAILED = "GET_ALL_VENDORS_FAILED";



export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const LOGIN_VENDOR = "LOGIN_VENDOR";
export const VENDOR_SUCCESS = "VENDOR_SUCCESS";
export const VENDOR_FAILED = "VENDOR_FAILED";

export const VENDOR_SIGNIN = "VENDOR_SIGNIN";
export const VENDOR_SIGNIN_SUCCESS = "VENDOR_SIGNIN_SUCCESS";
export const VENDOR_SIGNIN_FAILED = "VENDOR_SIGNIN_FAILED";

export const GET_DETAIL_VENDOR = "GET_DETAIL_VENDOR";
export const GET_DETAIL_VENDOR_SUCCESS = "GET_DETAIL_VENDOR_SUCCESS";
export const GET_DETAIL_VENDOR_FAILED = "GET_DETAIL_VENDOR_FAILED";

export const GET_LIKED_VENDORS = "GET_LIKED_VENDORS";
export const GET_LIKED_VENDORS_SUCCESS = "GET_LIKED_VENDORS_SUCCESS";
export const GET_LIKED_VENDORS_FAILED = "GET_LIKED_VENDORS_FAILED";


export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES"
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS"
export const GET_ALL_MESSAGES_FAILED = "GET_ALL_MESSAGES_FAILED"

export const GET_ALL_CHAT_MESSAGES = "GET_ALL_CHAT_MESSAGES"
export const GET_ALL_CHAT_MESSAGES_SUCCESS = "GET_ALL_CHAT_MESSAGES_SUCCESS"
export const GET_ALL_CHAT_MESSAGES_FAILED = "GET_ALL_CHAT_MESSAGES_FAILED"

export const UPDATE_CHAT_MESSAGES = "UPDATE_CHAT_MESSAGES"
export const UPDATE_CHAT_MESSAGES_SUCCESS = "UPDATE_CHAT_MESSAGES_SUCCESS"
export const UPDATE_CHAT_MESSAGES_FAILED = "UPDATE_CHAT_MESSAGES_FAILED"

export const UNSET_CONNECT_CHAT = "UNSET_CONNECT_CHAT"
export const SET_CONNECT_CHAT = "SET_CONNECT_CHAT"

export const GET_ALL_QUOTES = "GET_ALL_QUOTES"
export const GET_ALL_QUOTES_SUCCESS = "GET_ALL_QUOTES_SUCCESS"
export const GET_ALL_QUOTES_FAILED = "GET_ALL_QUOTES_FAILED"

export const SET_QUOTE = "SET_QUOTE"
export const DELETE_QUOTE = "DELETE_QUOTE"
//companydetail

